from __future__ import annotations

from pathlib import Path
from typing import Any


def build_base_stages(
    *,
    project_root: Path,
    python_bin: str,
    baseline_enabled: bool,
    intervention_enabled: bool,
    results_enabled: bool,
    baseline_grid: str,
    intervention_grid: str,
    baseline_runs_root: Path,
    intervention_runs_root: Path,
    pairs_csv: Path,
    pairs_json: Path,
    pair_mode: str,
    milestone_epochs: list[Any],
    explicit_pairs: list[Any],
    interpolation_cfg: str,
    barrier_cfg: str,
    path_compare_cfg: str,
    interpolation_out: Path,
    barrier_out: Path,
    path_compare_out: Path,
    geometry_cfg: str,
    geometry_out: Path,
    geometry_summary_csv: Path,
    results_out: Path,
    results_manifest: Path,
) -> list[dict[str, Any]]:
    return [
        {
            "stage": "baseline_train",
            "enabled": baseline_enabled,
            "command": ["bash", str((project_root / "experiments/run_lr_bs_grid.sh").resolve()), baseline_grid],
            "primary_output": str(baseline_runs_root),
            "note": "Launch or reuse baseline training grid",
        },
        {
            "stage": "trajectory_pairs",
            "enabled": baseline_enabled,
            "command": [
                python_bin,
                "-m",
                "ntempvh.pipeline.trajectory_pairs",
                "--runs_root",
                str(baseline_runs_root),
                "--out_csv",
                str(pairs_csv),
                "--out_json",
                str(pairs_json),
                "--pair_mode",
                pair_mode,
                "--milestone_epochs",
                *[str(value) for value in milestone_epochs],
                "--explicit_pairs",
                *[str(value) for value in explicit_pairs],
            ],
            "primary_output": str(pairs_json),
            "note": "Build within-run trajectory checkpoint pairs",
        },
        {
            "stage": "interpolation",
            "enabled": baseline_enabled,
            "command": [
                "bash",
                str((project_root / "experiments/run_interpolation_grid.sh").resolve()),
                str(pairs_csv),
                interpolation_cfg,
                str(interpolation_out),
            ],
            "primary_output": str(interpolation_out),
            "note": "Generate interpolation artifacts for trajectory pairs",
        },
        {
            "stage": "barrier",
            "enabled": baseline_enabled,
            "command": [
                "bash",
                str((project_root / "experiments/run_barrier_grid.sh").resolve()),
                str(interpolation_out),
                barrier_cfg,
                str(barrier_out),
            ],
            "primary_output": str(barrier_out),
            "note": "Compute baseline barrier artifacts from interpolations",
        },
        {
            "stage": "path_compare",
            "enabled": baseline_enabled,
            "command": [
                "bash",
                str((project_root / "experiments/run_path_compare_grid.sh").resolve()),
                str(pairs_csv),
                path_compare_cfg,
                str(path_compare_out),
            ],
            "primary_output": str(path_compare_out / "comparisons"),
            "note": "Compute chord-vs-observed comparison artifacts",
        },
        {
            "stage": "intervention_train",
            "enabled": intervention_enabled,
            "command": ["bash", str((project_root / "experiments/run_lr_bs_grid.sh").resolve()), intervention_grid],
            "primary_output": str(intervention_runs_root),
            "note": "Launch or reuse intervention training grid",
        },
        {
            "stage": "intervention_geometry",
            "enabled": intervention_enabled,
            "command": [
                "bash",
                str((project_root / "experiments/run_intervention_geometry_batch.sh").resolve()),
                str(intervention_runs_root),
                geometry_cfg,
                str(geometry_out),
            ],
            "primary_output": str(geometry_summary_csv),
            "note": "Run pre, post and final geometry for intervention runs",
        },
        {
            "stage": "results",
            "enabled": results_enabled,
            "command": [
                "bash",
                str((project_root / "experiments/run_results_pipeline.sh").resolve()),
                str(intervention_runs_root),
                str(path_compare_out),
                str(geometry_summary_csv),
                str(results_out),
            ],
            "primary_output": str(results_manifest),
            "note": "Aggregate final report-style machine-readable summaries",
        },
    ]
